# This file was generated by GoReleaser. DO NOT EDIT.
cask "antfly" do
  desc "antfly - A command line interface for running AntfyDB indexing"
  homepage "https://docs.antfly.io"
  version "0.0.0-dev2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "antfly"
  bash_completion "completions/antfly.bash"
  zsh_completion "completions/antfly.zsh"
  fish_completion "completions/antfly.fish"
  depends_on formula: [
      "antflycli",
    ]

  on_macos do
    url "https://releases.antfly.io/antfly/v0.0.0-dev2/antfly_0.0.0-dev2_Darwin_all.tar.gz"
    sha256 "2b007a4db6fc8b2b667584decce86a91febdce9e9cc324faaedea1a86557d337"
  end

  on_linux do
    on_intel do
      url "https://releases.antfly.io/antfly/v0.0.0-dev2/antfly_0.0.0-dev2_Linux_x86_64.tar.gz"
      sha256 "2412fed78a8a8f3b99226af229726845067659f8ed60a7fd2bdd2ec3eaf7cd43"
    end
    on_arm do
      url "https://releases.antfly.io/antfly/v0.0.0-dev2/antfly_0.0.0-dev2_Linux_arm64.tar.gz"
      sha256 "85e0c1695c5b0c413e97b107cc223bfb52624ecf7ee947689c55ed286e457278"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/antfly"]
    end
  end

  # No zap stanza required
end
