# This file was generated by GoReleaser. DO NOT EDIT.
cask "antflycli" do
  name "antflycli"
  desc "antflycli - A command line interface for interacting with AntfyDB"
  homepage "https://antfly.io"
  version "0.0.13"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "antflycli"
  bash_completion "completions/antflycli.bash"
  zsh_completion "completions/antflycli.zsh"
  fish_completion "completions/antflycli.fish"

  on_macos do
    on_arm do
      url "https://releases.antfly.io/antfly/v#{version}/antfly_#{version}_Darwin_arm64.tar.gz"
      sha256 "c46b9dae5f118c87b54e2b2e428a804e0465643d893f8bc7ac449612e051285e"
    end
  end

  on_linux do
    on_intel do
      url "https://releases.antfly.io/antfly/v#{version}/antfly_#{version}_Linux_x86_64.tar.gz"
      sha256 "caf8956d077a233d516b383e394e9efeb8fe9f4639a032a2be4e86a6da1e8eab"
    end
    on_arm do
      url "https://releases.antfly.io/antfly/v#{version}/antfly_#{version}_Linux_arm64.tar.gz"
      sha256 "83806592ed42b458f4f28cd28fdf2aacb46a9317b1c1dc29f36e7f1d4f04f5b1"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/antflycli"]
    end
  end

  # No zap stanza required
end
