# This file was generated by GoReleaser. DO NOT EDIT.
cask "antfly-onnx" do
  name "antfly-onnx"
  desc "antfly with ONNX Runtime - includes ML inference support for embeddings"
  homepage "https://docs.antfly.io"
  version "0.0.0-dev26"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "antfly"
  bash_completion "completions/antfly.bash"
  zsh_completion "completions/antfly.zsh"
  fish_completion "completions/antfly.fish"

  on_macos do
    on_intel do
      url "https://releases.antfly.io/antfly/v#{version}/antfly-onnx_#{version}_Darwin_x86_64.tar.gz"
      sha256 "50fe21b2abf30da1341cf9007adfa82baaf0287a4d515c088f971eceeb83343f"
    end
    on_arm do
      url "https://releases.antfly.io/antfly/v#{version}/antfly-onnx_#{version}_Darwin_arm64.tar.gz"
      sha256 "3a677a6f44b0af4ed59d7a6270cce906d5df34148d3b154cde69b787c186fda2"
    end
  end

  on_linux do
    on_intel do
      url "https://releases.antfly.io/antfly/v#{version}/antfly-onnx_#{version}_Linux_x86_64.tar.gz"
      sha256 "790e16be84a9b2c3e907a35874795603c452df5ecab0351f88f7ecc10c283f95"
    end
    on_arm do
      url "https://releases.antfly.io/antfly/v#{version}/antfly-onnx_#{version}_Linux_arm64.tar.gz"
      sha256 "c11880e9bc67ef8bc7b327fab19a241843ad06f5ae2ae809cfaa7fd6ec112ecc"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/antfly"]
      # Also clear quarantine on bundled libraries
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lib"]
    end
  end

  caveats do
    "antfly-onnx includes bundled ONNX Runtime libraries for ML inference."
    "The libraries are installed in the lib/ directory alongside the binary."
    ""
    "For the standard version without ML dependencies, use:"
    "  brew install --cask antfly"
  end

  # No zap stanza required
end
