# This file was generated by GoReleaser. DO NOT EDIT.
cask "antflycli" do
  name "antflycli"
  desc "antflycli - A command line interface for interacting with AntfyDB"
  homepage "https://antfly.io"
  version "0.0.0-dev35"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "antflycli"
  bash_completion "completions/antflycli.bash"
  zsh_completion "completions/antflycli.zsh"
  fish_completion "completions/antflycli.fish"

  on_macos do
    url "https://releases.antfly.io/antfly/v#{version}/antfly_#{version}_Darwin_all.tar.gz"
    sha256 "948b18e0cb8a8956702f0bc08694f1d58f623857bdcff21cd616c764ea7dd43d"
  end

  on_linux do
    on_intel do
      url "https://releases.antfly.io/antfly/v#{version}/antfly_#{version}_Linux_x86_64.tar.gz"
      sha256 "31264f2be5246bd7377300a28364ee66aa01fd37e173ccf6a5a059974660e204"
    end
    on_arm do
      url "https://releases.antfly.io/antfly/v#{version}/antfly_#{version}_Linux_arm64.tar.gz"
      sha256 "1144aebaa9967ba291a390ee570fa5c47114ecaeeb6f28452caf6b98aea9065e"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/antflycli"]
    end
  end

  # No zap stanza required
end
