# This file was generated by GoReleaser. DO NOT EDIT.
cask "antfly-onnx" do
  name "antfly-onnx"
  desc "antfly with ONNX Runtime - includes ML inference support for embeddings"
  homepage "https://docs.antfly.io"
  version "0.0.0-dev50"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "antfly"
  bash_completion "completions/antfly.bash"
  zsh_completion "completions/antfly.zsh"
  fish_completion "completions/antfly.fish"

  on_macos do
    on_intel do
      url "https://releases.antfly.io/antfly/v#{version}/antfly-onnx_#{version}_Darwin_x86_64.tar.gz"
      sha256 "94bfc76764e30561fb8d199721e832912d043a073c64ae2ce266e8fa209552bf"
    end
    on_arm do
      url "https://releases.antfly.io/antfly/v#{version}/antfly-onnx_#{version}_Darwin_arm64.tar.gz"
      sha256 "b217e80b765291ddee10dce73311397471c233752114cdbbd030021d4989e264"
    end
  end

  on_linux do
    on_intel do
      url "https://releases.antfly.io/antfly/v#{version}/antfly-onnx_#{version}_Linux_x86_64.tar.gz"
      sha256 "261ecb0dee9e1d606b78cf968e33793b114506d535b364a93cd8df33289f01c4"
    end
    on_arm do
      url "https://releases.antfly.io/antfly/v#{version}/antfly-onnx_#{version}_Linux_arm64.tar.gz"
      sha256 "e440990bdaf4d9c57e36b747c0d839209f42a982dee12bb2bc0cceaf1787c309"
    end
  end

  conflicts_with cask: [
      "antfly",
    ]

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/antfly"]
      # Also clear quarantine on bundled libraries
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lib"]
    end
  end

  caveats do
    "antfly-onnx includes bundled ONNX Runtime libraries for ML inference."
    "The libraries are installed in the lib/ directory alongside the binary."
    ""
    "For the standard version without ML dependencies, use:"
    "  brew install --cask antfly"
  end

  # No zap stanza required
end
