# This file was generated by GoReleaser. DO NOT EDIT.
cask "antfly-omni" do
  name "antfly-omni"
  desc "antfly with ONNX Runtime + XLA - multi-backend ML inference"
  homepage "https://docs.antfly.io"
  version "0.0.8-rc1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "antfly"
  bash_completion "completions/antfly.bash"
  zsh_completion "completions/antfly.zsh"
  fish_completion "completions/antfly.fish"

  on_macos do
    on_intel do
      url "https://releases.antfly.io/antfly/v#{version}/antfly-omni_#{version}_Darwin_x86_64.tar.gz"
      sha256 "94a02217bb82769bf9f2c47f705a52fa411d3ddd1ed6ab356f28c30fd7dc5ece"
    end
    on_arm do
      url "https://releases.antfly.io/antfly/v#{version}/antfly-omni_#{version}_Darwin_arm64.tar.gz"
      sha256 "06c0f24594fa39ddc213f6a84fdd0912c71a6cbc41a78e7a3de2586146ff7e03"
    end
  end

  on_linux do
    on_intel do
      url "https://releases.antfly.io/antfly/v#{version}/antfly-omni_#{version}_Linux_x86_64.tar.gz"
      sha256 "8d5b9c2d04bf6971c8911c550437b46f6d95659dccaeaa7186dac21a78aa4118"
    end
    on_arm do
      url "https://releases.antfly.io/antfly/v#{version}/antfly-omni_#{version}_Linux_arm64.tar.gz"
      sha256 "722e714bf06dbeb588175980fcf7e6da5de8ef3684b68a5527a75c024bc8fcec"
    end
  end

  conflicts_with cask: [
      "antfly",
    ]

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/antfly"]
      # Also clear quarantine on bundled libraries
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lib"]
    end
  end

  caveats do
    "antfly-omni includes both ONNX Runtime and XLA backends for ML inference."
    "Bundled libraries are auto-discovered from lib/ next to the binary."
    ""
    "Backend priority can be configured via TERMITE_BACKEND_PRIORITY env var:"
    "  export TERMITE_BACKEND_PRIORITY="onnx,xla,go""
    ""
    "For the standard version without ML dependencies, use:"
    "  brew install --cask antfly"
  end

  # No zap stanza required
end
