# This file was generated by GoReleaser. DO NOT EDIT.
cask "antfly" do
  desc "antfly - A command line interface for running AntfyDB indexing"
  homepage "https://docs.antfly.io"
  version "0.0.0-dev2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "antfly"
  depends_on formula: [
      "antflycli",
    ]

  on_macos do
    url "https://releases.antfly.io/antfly/v0.0.0-dev2/antfly_0.0.0-dev2_Darwin_all.tar.gz"
    sha256 "4b49c5df75f800df5a807893f01ef069324305edea07f499e62a66978c1599d3"
  end

  on_linux do
    on_intel do
      url "https://releases.antfly.io/antfly/v0.0.0-dev2/antfly_0.0.0-dev2_Linux_x86_64.tar.gz"
      sha256 "066c18986c996cd7db5b7ffa287a99aa7b9cdd8e83a6852e00c8c154e60cffed"
    end
    on_arm do
      url "https://releases.antfly.io/antfly/v0.0.0-dev2/antfly_0.0.0-dev2_Linux_arm64.tar.gz"
      sha256 "381fe3144ad8802455b015f6d8e06c8d78dbc00322f594b768ef809b58eb6ebf"
    end
  end

  preflight do
    bin.install "antfly" => "antfly"
    output = Utils.popen_read("SHELL=bash #{bin}/antfly completion bash")
    (bash_completion/"antfly").write output
    output = Utils.popen_read("SHELL=zsh #{bin}/antfly completion zsh")
    (zsh_completion/"_antfly").write output
    prefix.install_metafiles
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/antfly"]
    end
  end

  # No zap stanza required
end
