# This file was generated by GoReleaser. DO NOT EDIT.
cask "antfly-omni" do
  name "antfly-omni"
  desc "antfly with ONNX Runtime + XLA - multi-backend ML inference"
  homepage "https://docs.antfly.io"
  version "0.0.0-dev57"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "antfly"
  bash_completion "completions/antfly.bash"
  zsh_completion "completions/antfly.zsh"
  fish_completion "completions/antfly.fish"

  on_macos do
    on_intel do
      url "https://releases.antfly.io/antfly/v#{version}/antfly-omni_#{version}_Darwin_x86_64.tar.gz"
      sha256 "c7abd887caef08250a0dbb0a6b041b7f1c0568ba856244e21f00a33d73d380a3"
    end
    on_arm do
      url "https://releases.antfly.io/antfly/v#{version}/antfly-omni_#{version}_Darwin_arm64.tar.gz"
      sha256 "333f1d0abdefc55b0ea325d1eead848a6e60a0445b85312d9c9de1df79b68c5b"
    end
  end

  on_linux do
    on_intel do
      url "https://releases.antfly.io/antfly/v#{version}/antfly-omni_#{version}_Linux_x86_64.tar.gz"
      sha256 "687ed41a20a8ca3ac49c7e40bd671b7dcac8c83a327ee59e471f72cb76118fdf"
    end
    on_arm do
      url "https://releases.antfly.io/antfly/v#{version}/antfly-omni_#{version}_Linux_arm64.tar.gz"
      sha256 "4680e5e0809d02229cd274451c66161518d31ae34b68fe91cd2ee0dd96f18c8a"
    end
  end

  conflicts_with cask: [
      "antfly",
    ]

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/antfly"]
      # Also clear quarantine on bundled libraries
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lib"]
    end
  end

  caveats do
    "antfly-omni includes both ONNX Runtime and XLA backends for ML inference."
    "Bundled libraries are auto-discovered from lib/ next to the binary."
    ""
    "Backend priority can be configured via TERMITE_BACKEND_PRIORITY env var:"
    "  export TERMITE_BACKEND_PRIORITY="onnx,xla,go""
    ""
    "For the standard version without ML dependencies, use:"
    "  brew install --cask antfly"
  end

  # No zap stanza required
end
