# This file was generated by GoReleaser. DO NOT EDIT.
cask "antflycli" do
  name "antflycli"
  desc "antflycli - A command line interface for interacting with AntfyDB"
  homepage "https://antfly.io"
  version "0.0.12"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "antflycli"
  bash_completion "completions/antflycli.bash"
  zsh_completion "completions/antflycli.zsh"
  fish_completion "completions/antflycli.fish"

  on_macos do
    on_arm do
      url "https://releases.antfly.io/antfly/v#{version}/antfly_#{version}_Darwin_arm64.tar.gz"
      sha256 "a3bcdcc0a00c3d78fd70ae4e635bdcc55da7ad601bdfe516f9b6ca6e8637cff8"
    end
  end

  on_linux do
    on_intel do
      url "https://releases.antfly.io/antfly/v#{version}/antfly_#{version}_Linux_x86_64.tar.gz"
      sha256 "dd45fd4f7d26d5e05070dad9108e631e32532ffe5ba282cfd87e3cf86c58be0d"
    end
    on_arm do
      url "https://releases.antfly.io/antfly/v#{version}/antfly_#{version}_Linux_arm64.tar.gz"
      sha256 "d7e20211ba0348513910d482bc7e451456fa3e481a9a96af751ac4577ff56367"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/antflycli"]
    end
  end

  # No zap stanza required
end
