# This file was generated by GoReleaser. DO NOT EDIT.
cask "antfly-omni" do
  name "antfly-omni"
  desc "antfly with ONNX Runtime + XLA - multi-backend ML inference"
  homepage "https://docs.antfly.io"
  version "0.0.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "antfly"
  bash_completion "completions/antfly.bash"
  zsh_completion "completions/antfly.zsh"
  fish_completion "completions/antfly.fish"

  on_macos do
    on_intel do
      url "https://releases.antfly.io/antfly/v#{version}/antfly-omni_#{version}_Darwin_x86_64.tar.gz"
      sha256 "4486a9776d99dfa975b1103fda17420fdcbbc2326a90f3862ceb45a6f0291956"
    end
    on_arm do
      url "https://releases.antfly.io/antfly/v#{version}/antfly-omni_#{version}_Darwin_arm64.tar.gz"
      sha256 "981796e34cc3e2f91e655ab9eb2affdbe18b1fb309d2832046fe0248741a0b07"
    end
  end

  on_linux do
    on_intel do
      url "https://releases.antfly.io/antfly/v#{version}/antfly-omni_#{version}_Linux_x86_64.tar.gz"
      sha256 "074d12c21daa686d258f119bbd0385fdc36e0e342c8b99f62a24e3378e6e65d6"
    end
    on_arm do
      url "https://releases.antfly.io/antfly/v#{version}/antfly-omni_#{version}_Linux_arm64.tar.gz"
      sha256 "5aa3a620233b9ad3d24138a7196411556bb2f688487dcd35c1a8fad9ac724761"
    end
  end

  conflicts_with cask: [
      "antfly",
    ]

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/antfly"]
      # Also clear quarantine on bundled libraries
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lib"]
    end
  end

  caveats do
    "antfly-omni includes both ONNX Runtime and XLA backends for ML inference."
    "Bundled libraries are auto-discovered from lib/ next to the binary."
    ""
    "Backend priority can be configured via TERMITE_BACKEND_PRIORITY env var:"
    "  export TERMITE_BACKEND_PRIORITY="onnx,xla,go""
    ""
    "For the standard version without ML dependencies, use:"
    "  brew install --cask antfly"
  end

  # No zap stanza required
end
