# This file was generated by GoReleaser. DO NOT EDIT.
cask "antfly-onnx" do
  name "antfly-onnx"
  desc "antfly with ONNX Runtime - includes ML inference support for embeddings"
  homepage "https://docs.antfly.io"
  version "0.0.0-dev49"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "antfly"
  bash_completion "completions/antfly.bash"
  zsh_completion "completions/antfly.zsh"
  fish_completion "completions/antfly.fish"

  on_macos do
    on_intel do
      url "https://releases.antfly.io/antfly/v#{version}/antfly-onnx_#{version}_Darwin_x86_64.tar.gz"
      sha256 "304cbd8bf65abe191977bc4052abfb42e343fa5bf9537b1d25dfb21c69a3ac81"
    end
    on_arm do
      url "https://releases.antfly.io/antfly/v#{version}/antfly-onnx_#{version}_Darwin_arm64.tar.gz"
      sha256 "8d24a947d6d66046149f729b7e33724fd64ce9e8cc3723034608b8ff00d05f78"
    end
  end

  on_linux do
    on_intel do
      url "https://releases.antfly.io/antfly/v#{version}/antfly-onnx_#{version}_Linux_x86_64.tar.gz"
      sha256 "8f1c9f4ab1e5fc6abb16740f7a34e2ec6a36eb4c2fecd617ba28a2ad9b51acc0"
    end
    on_arm do
      url "https://releases.antfly.io/antfly/v#{version}/antfly-onnx_#{version}_Linux_arm64.tar.gz"
      sha256 "49dbeb44f02fb58156bfbf3bbbac0ddbe1a353cabd3a0d9d62e9898b1ab511a4"
    end
  end

  conflicts_with cask: [
      "antfly",
    ]

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/antfly"]
      # Also clear quarantine on bundled libraries
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lib"]
    end
  end

  caveats do
    "antfly-onnx includes bundled ONNX Runtime libraries for ML inference."
    "The libraries are installed in the lib/ directory alongside the binary."
    ""
    "For the standard version without ML dependencies, use:"
    "  brew install --cask antfly"
  end

  # No zap stanza required
end
