# This file was generated by GoReleaser. DO NOT EDIT.
cask "antfly" do
  name "antfly"
  desc "antfly - A command line interface for running AntfyDB indexing"
  homepage "https://docs.antfly.io"
  version "0.0.0-dev4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "antfly"
  bash_completion "completions/antfly.bash"
  zsh_completion "completions/antfly.zsh"
  fish_completion "completions/antfly.fish"

  on_macos do
    url "https://releases.antfly.io/antfly/#{version}/antfly_#{version}_Darwin_all.tar.gz"
    sha256 "ef4f197b701087a8676dbca1c2bc3f028435818fd9197cd8cd02f6f62f1cc2ef"
  end

  on_linux do
    on_intel do
      url "https://releases.antfly.io/antfly/#{version}/antfly_#{version}_Linux_x86_64.tar.gz"
      sha256 "689df5ab9145f88f97684f440799774301e8d7a645b0f79116ee7603ff1303cd"
    end
    on_arm do
      url "https://releases.antfly.io/antfly/#{version}/antfly_#{version}_Linux_arm64.tar.gz"
      sha256 "9b4d6b7618d3d0919ddfc9418426b102c5fcd310e905f13014c5ccec88eac085"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/antfly"]
    end
  end

  # No zap stanza required
end
