# This file was generated by GoReleaser. DO NOT EDIT.
cask "termite" do
  name "termite"
  desc "Termite - ML inference service with ONNX Runtime + XLA multi-backend inference"
  homepage "https://docs.antfly.io/docs/guides/termite"
  version "0.0.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "termite"

  on_macos do
    on_arm do
      url "https://releases.antfly.io/termite/v#{version}/termite-omni_#{version}_Darwin_arm64.tar.gz"
      sha256 "268de8cba4c3befa02f84a51a51537db3aeed5149a7324ca2b0ec2d11e9e704b"
    end
  end

  on_linux do
    on_intel do
      url "https://releases.antfly.io/termite/v#{version}/termite-omni_#{version}_Linux_x86_64.tar.gz"
      sha256 "8ebef1b235db267e69a3d69e7c54d2bbc4c7286e464910a457eb873af6b5167a"
    end
    on_arm do
      url "https://releases.antfly.io/termite/v#{version}/termite-omni_#{version}_Linux_arm64.tar.gz"
      sha256 "09197934857b285fb812c7db08d330e7aafca03e759fe6c71b9ab40b543f7738"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/termite", "#{staged_path}/lib"]
    end
  end

  caveats do
    "termite includes both ONNX Runtime and XLA backends for ML inference."
    "Bundled libraries are auto-discovered from lib/ next to the binary."
  end

  # No zap stanza required
end
