# This file was generated by GoReleaser. DO NOT EDIT.
cask "termite-omni" do
  name "termite-omni"
  desc "Termite with ONNX Runtime + XLA - multi-backend ML inference"
  homepage "https://docs.antfly.io/docs/guides/termite"
  version "0.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "termite"

  on_macos do
    on_intel do
      url "https://github.com/antflydb/termite/releases/download/v#{version}/termite-omni_#{version}_Darwin_x86_64.tar.gz"
      sha256 "245fcea2e69e5f35feb198f7fa7d355c6ff4382ed370be87fb39df740afda335"
    end
    on_arm do
      url "https://github.com/antflydb/termite/releases/download/v#{version}/termite-omni_#{version}_Darwin_arm64.tar.gz"
      sha256 "8b7d223798d49c4d3f58ea76f498b15fe93a40cd363f8ed07880a722538055ec"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/antflydb/termite/releases/download/v#{version}/termite-omni_#{version}_Linux_x86_64.tar.gz"
      sha256 "078557d752c60e61cc90c7ecc30b302b3c77a7e7cd9c2947a813fe7f1ca4926b"
    end
    on_arm do
      url "https://github.com/antflydb/termite/releases/download/v#{version}/termite-omni_#{version}_Linux_arm64.tar.gz"
      sha256 "831332f7fb47daf9abe4c5acee2da8f72aa44137358848529aad666e99a2bd5d"
    end
  end

  conflicts_with cask: [
      "termite",
      "termite-onnx",
    ]

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/termite"]
      # Also clear quarantine on bundled libraries
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lib"]
    end
  end

  caveats do
    "termite-omni includes both ONNX Runtime and XLA backends for ML inference."
    "Bundled libraries are auto-discovered from lib/ next to the binary."
    ""
    "Backend priority can be configured in termite.yaml:"
    "  backend_priority: ["onnx:coreml", "xla:cpu", "go"]"
    ""
    "For single-backend versions:"
    "  brew install --cask termite      # Pure Go (no acceleration)"
    "  brew install --cask termite-onnx # ONNX Runtime only"
  end

  # No zap stanza required
end
