# This file was generated by GoReleaser. DO NOT EDIT.
cask "termite-omni" do
  name "termite-omni"
  desc "Termite with ONNX Runtime + XLA - multi-backend ML inference"
  homepage "https://docs.antfly.io/docs/guides/termite"
  version "0.0.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "termite"

  on_macos do
    on_arm do
      url "https://github.com/antflydb/termite/releases/download/v#{version}/termite-omni_#{version}_Darwin_arm64.tar.gz"
      sha256 "6f7442b3111c7d83a9c358247eec780892002b0c64d3dae752b73c26ce81df49"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/antflydb/termite/releases/download/v#{version}/termite-omni_#{version}_Linux_x86_64.tar.gz"
      sha256 "efc092c9f88ccb471050f2979418b3744174c8b7ee0370778e51a6efdf041d78"
    end
    on_arm do
      url "https://github.com/antflydb/termite/releases/download/v#{version}/termite-omni_#{version}_Linux_arm64.tar.gz"
      sha256 "577659300ab45300c7a90d3292c881abe55388ca6be07263217363e43d6b55d4"
    end
  end

  conflicts_with cask: [
      "termite",
    ]

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/termite"]
      # Also clear quarantine on bundled libraries
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lib"]
    end
  end

  caveats do
    "termite-omni includes both ONNX Runtime and XLA backends for ML inference."
    "Bundled libraries are auto-discovered from lib/ next to the binary."
    ""
    "Backend priority can be configured in termite.yaml:"
    "  backend_priority: ["onnx:coreml", "xla:cpu", "go"]"
    ""
    "For the standard version without ML dependencies, use:"
    "  brew install --cask termite"
  end

  # No zap stanza required
end
