# This file was generated by GoReleaser. DO NOT EDIT.
cask "termite-onnx" do
  name "termite-onnx"
  desc "Termite with ONNX Runtime - includes ML inference acceleration"
  homepage "https://docs.antfly.io/docs/guides/termite"
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "termite"

  on_macos do
    on_intel do
      url "https://github.com/antflydb/termite/releases/download/v#{version}/termite-onnx_#{version}_Darwin_x86_64.tar.gz"
      sha256 "4625d239ae10e4a2fafa14f24dd86130de18c1ea0f32eb7aed089c458124218b"
    end
    on_arm do
      url "https://github.com/antflydb/termite/releases/download/v#{version}/termite-onnx_#{version}_Darwin_arm64.tar.gz"
      sha256 "aeb8ba2356fda58702b81ac82216953bc37fa2fa167a9b6778a8070af42cabe8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/antflydb/termite/releases/download/v#{version}/termite-onnx_#{version}_Linux_x86_64.tar.gz"
      sha256 "9e09c1933ef059cb316b924274db477b2098c03b094ab3c17fbf0d9ec2ae29e6"
    end
    on_arm do
      url "https://github.com/antflydb/termite/releases/download/v#{version}/termite-onnx_#{version}_Linux_arm64.tar.gz"
      sha256 "bd9a60777a7f6d8d4bd085b263ca5da679cc2df0a571918e069d63c91d00f081"
    end
  end

  conflicts_with cask: [
      "termite",
    ]

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/termite"]
      # Also clear quarantine on bundled libraries
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lib"]
    end
  end

  caveats do
    "termite-onnx includes bundled ONNX Runtime libraries for ML inference."
    "The libraries are installed in the lib/ directory alongside the binary."
    ""
    "For the standard version without ML dependencies, use:"
    "  brew install --cask termite"
  end

  # No zap stanza required
end
