# This file was generated by GoReleaser. DO NOT EDIT.
cask "termite-omni" do
  name "termite-omni"
  desc "Termite with ONNX Runtime + XLA - multi-backend ML inference"
  homepage "https://docs.antfly.io/docs/guides/termite"
  version "0.0.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "termite"

  on_macos do
    on_arm do
      url "https://releases.antfly.io/termite/v#{version}/termite-omni_#{version}_Darwin_arm64.tar.gz"
      sha256 "bcf4a45f41c5258f8aaeb524846bafddcc8762b14161099161f24a4a7f24bc05"
    end
  end

  on_linux do
    on_intel do
      url "https://releases.antfly.io/termite/v#{version}/termite-omni_#{version}_Linux_x86_64.tar.gz"
      sha256 "8749efb39434d99646e8fa86295179df071781c7cc9558f687b4dd48e13415b6"
    end
    on_arm do
      url "https://releases.antfly.io/termite/v#{version}/termite-omni_#{version}_Linux_arm64.tar.gz"
      sha256 "3b11ea99b39af295587ee610aeee15e89977c2095b564250c32fe477cb888ffb"
    end
  end

  conflicts_with cask: [
      "termite",
    ]

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/termite"]
      # Also clear quarantine on bundled libraries
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lib"]
    end
  end

  caveats do
    "termite-omni includes both ONNX Runtime and XLA backends for ML inference."
    "Bundled libraries are auto-discovered from lib/ next to the binary."
    ""
    "Backend priority can be configured in termite.yaml:"
    "  backend_priority: ['onnx:coreml', 'xla:cpu', 'go']"
    ""
    "For the standard version without ML dependencies, use:"
    "  brew install --cask termite"
  end

  # No zap stanza required
end
