# This file was generated by GoReleaser. DO NOT EDIT.
cask "termite-onnx" do
  name "termite-onnx"
  desc "Termite with ONNX Runtime - includes ML inference acceleration"
  homepage "https://docs.antfly.io/docs/guides/termite"
  version "0.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "termite"

  on_macos do
    on_intel do
      url "https://github.com/antflydb/termite/releases/download/v#{version}/termite-onnx_#{version}_Darwin_x86_64.tar.gz"
      sha256 "369fabc8f703c28af6c6fe600cb8a7dc8b91cd252126eeaa6913de10c23c7a71"
    end
    on_arm do
      url "https://github.com/antflydb/termite/releases/download/v#{version}/termite-onnx_#{version}_Darwin_arm64.tar.gz"
      sha256 "96b01dbf682da6a6ef783786341081923239c3877a5f714c5597a4764ad9fe7d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/antflydb/termite/releases/download/v#{version}/termite-onnx_#{version}_Linux_x86_64.tar.gz"
      sha256 "d5c9e7deafb513104ed20a945fee29c9aaeebb2dde250b0a5c65272d1e869eef"
    end
    on_arm do
      url "https://github.com/antflydb/termite/releases/download/v#{version}/termite-onnx_#{version}_Linux_arm64.tar.gz"
      sha256 "1c717d2c4d0046bc7143ebfd99b6eabda78a0795acc677e6aaa38adefc2ad516"
    end
  end

  conflicts_with cask: [
      "termite",
    ]

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/termite"]
      # Also clear quarantine on bundled libraries
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lib"]
    end
  end

  caveats do
    "termite-onnx includes bundled ONNX Runtime libraries for ML inference."
    "The libraries are installed in the lib/ directory alongside the binary."
    ""
    "For the standard version without ML dependencies, use:"
    "  brew install --cask termite"
  end

  # No zap stanza required
end
