# This file was generated by GoReleaser. DO NOT EDIT.
cask "termite" do
  name "termite"
  desc "Termite - ML inference service with ONNX Runtime + XLA multi-backend inference"
  homepage "https://docs.antfly.io/docs/guides/termite"
  version "0.0.10"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "termite"

  on_macos do
    on_arm do
      url "https://releases.antfly.io/termite/v#{version}/termite-omni_#{version}_Darwin_arm64.tar.gz"
      sha256 "ae0ed52ec4da9e1cd1c0232311e68da35115818e5a0e8483ae3fde5b59c4bfe0"
    end
  end

  on_linux do
    on_intel do
      url "https://releases.antfly.io/termite/v#{version}/termite-omni_#{version}_Linux_x86_64.tar.gz"
      sha256 "a1de203681b1abd70d672fa7cf94ed5f50e29dceaa526156dabfcf5067b68f66"
    end
    on_arm do
      url "https://releases.antfly.io/termite/v#{version}/termite-omni_#{version}_Linux_arm64.tar.gz"
      sha256 "b546a790fa2f5e01013db8400a96f94088664d9980bf743f316f0777edfa2182"
    end
  end

  postflight do
    if OS.mac?
      system_command "/bin/chmod", args: ["-R", "u+rw", "#{staged_path}/lib"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/termite", "#{staged_path}/lib"]
    end
  end

  caveats do
    "termite includes both ONNX Runtime and XLA backends for ML inference."
    "Bundled libraries are auto-discovered from lib/ next to the binary."
  end

  # No zap stanza required
end
