# This file was generated by GoReleaser. DO NOT EDIT.
cask "termite" do
  name "termite"
  desc "Termite - ML inference service for embeddings, chunking, and reranking"
  homepage "https://docs.antfly.io/docs/guides/termite"
  version "0.0.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "termite"

  on_macos do
    on_arm do
      url "https://github.com/antflydb/termite/releases/download/v#{version}/termite_#{version}_Darwin_arm64.tar.gz"
      sha256 "f7ec71cf230e5a8b3cba755642b1c751231366e0e12a34fe8773615d670935c1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/antflydb/termite/releases/download/v#{version}/termite_#{version}_Linux_x86_64.tar.gz"
      sha256 "8470eee8a1a75af4f9a85f996205626d52c0bd65a23a43f80917eb9bfffd6112"
    end
    on_arm do
      url "https://github.com/antflydb/termite/releases/download/v#{version}/termite_#{version}_Linux_arm64.tar.gz"
      sha256 "44578347436eb4e86ca52ba7dc6731fd677e306a05b70bd96ba80659582d7a4e"
    end
  end

  conflicts_with cask: [
      "termite-omni",
    ]

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/termite"]
    end
  end

  # No zap stanza required
end
