# This file was generated by GoReleaser. DO NOT EDIT.
cask "termite-onnx" do
  name "termite-onnx"
  desc "Termite with ONNX Runtime - includes ML inference acceleration"
  homepage "https://docs.antfly.io/docs/guides/termite"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "termite"

  on_macos do
    on_intel do
      url "https://github.com/antflydb/termite/releases/download/v#{version}/termite-onnx_#{version}_Darwin_x86_64.tar.gz"
      sha256 "04e6c46df248613f6937d8b5725c4eabae9ef83c42f908b3fb50e81e049cf834"
    end
    on_arm do
      url "https://github.com/antflydb/termite/releases/download/v#{version}/termite-onnx_#{version}_Darwin_arm64.tar.gz"
      sha256 "4d761a4b15ab4a2d31bb574a73b1e8e77b9e76cf6f3a859903dc53040be5af2c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/antflydb/termite/releases/download/v#{version}/termite-onnx_#{version}_Linux_x86_64.tar.gz"
      sha256 "cdd3f7228c7ef2d2b0b43c60ab361348fe8a0de12195fe6dded1374fcc51e8f0"
    end
    on_arm do
      url "https://github.com/antflydb/termite/releases/download/v#{version}/termite-onnx_#{version}_Linux_arm64.tar.gz"
      sha256 "4f7949a56ceda6c3f899c12be46532d9a9321bed0d1b9741def07c0dac8485b2"
    end
  end

  conflicts_with cask: [
      "termite",
    ]

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/termite"]
      # Also clear quarantine on bundled libraries
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lib"]
    end
  end

  caveats do
    "termite-onnx includes bundled ONNX Runtime libraries for ML inference."
    "The libraries are installed in the lib/ directory alongside the binary."
    ""
    "For the standard version without ML dependencies, use:"
    "  brew install --cask termite"
  end

  # No zap stanza required
end
