name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-13 # amd64
          - macos-latest # arm64
          - ubuntu-latest # amd64
        product:
          - antfly
          - antflycli
    name: ${{ matrix.product }} cask tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install ${{ matrix.product }} cask
        run: ${{ runner.os == 'Linux' && '/home/linuxbrew/.linuxbrew/bin/brew' || 'brew' }} install ./Casks/${{matrix.product }}.rb
      - name: Test ${{ matrix.product }} cask
        run: ${{ runner.os == 'Linux' && '/home/linuxbrew/.linuxbrew/bin/brew' || 'brew' }} test ./Casks/${{ matrix.product }}.rb
